### ISSUE TITLE
Request - CDN

### ISSUE THREAD

**Issue by IOIIOOIO** [vladocar/Scribble-Font#1]
Hi, if possible it would be awesome if you could host this on a CDN? I want to use it in CodePen.

**Comment by vladocar** [comment]
Great Idea!

You can use the following CDN:

https://unpkg.com/scribble-font@1.0.0/scribble-webfont.woff
https://unpkg.com/scribble-font@1.0.0/scribble-webfont.woff2
https://unpkg.com/scribble-font@1.0.0/font/Scribble.ttf
